modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/thebrightspark/SparksTools/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sparks-tools"
logoFile="banner.png"

[[mods]]
    modId="sparkstools"
    version="${file.jarVersion}"
    displayName="SparksTools"
    authors="bright_spark"
    description='''
    Successor to Sparks Hammers, but now adding all kinds of tools!
    '''

[[dependencies.sparkstools]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sparkstools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.sparkstools]]
    modId="ksparklib"
    mandatory=true
    versionRange="[1,)"
    ordering="BEFORE"
    side="BOTH"